"""Reset data generated by an interactive dashboard run.

Imported machine, prediction, inventory, maintenance, and historical purchase
order data are source-of-truth seed data and are deliberately preserved.
"""

from __future__ import annotations

import os

from sqlalchemy import delete, inspect

from .connection import SessionLocal, database_enabled, engine
from .models import (
    ActionTask,
    AuthenticationEvent,
    ProcurementRequest,
    ProcurementRequestItem,
    ProcurementStatusHistory,
    TaskActionHistory,
)


RUNTIME_MODELS = (
    AuthenticationEvent,
    TaskActionHistory,
    ProcurementStatusHistory,
    ProcurementRequestItem,
    ActionTask,
    ProcurementRequest,
)


def reset_on_exit_enabled() -> bool:
    return os.getenv("DB_RESET_ON_EXIT", "false").strip().lower() in {"1", "true", "yes", "on"}


def reset_runtime_data() -> dict[str, int]:
    """Delete dashboard-generated rows in foreign-key-safe order."""
    if not database_enabled():
        return {}
    available = set(inspect(engine).get_table_names())
    deleted: dict[str, int] = {}
    with SessionLocal.begin() as session:
        for model in RUNTIME_MODELS:
            table_name = model.__tablename__
            if table_name not in available:
                continue
            result = session.execute(delete(model))
            deleted[table_name] = max(int(result.rowcount or 0), 0)
    return deleted


def main() -> None:
    deleted = reset_runtime_data()
    summary = ", ".join(f"{name}={count}" for name, count in deleted.items())
    print(f"runtime data reset: {summary or 'disabled'}")


if __name__ == "__main__":
    main()
